### ISSUE TITLE
Misleading part in Readme

### ISSUE THREAD

**Issue by aticie** [masleeper/osurandomdl#1]
In the Readme it says:

>  though I doubt anybody will find this unless I tell them lol.

This is misleading because I found this repository without you telling me about it.

Also on an unrelated note, keep your api key in an environment variable or read it from a file. Don't commit it please :/ (I can see yours in APICaller.py)

And you might want to revoke your current one ;) 

Good luck on your project!

**Comment by masleeper** [comment]
Yeah you're right, shouldn't have committed my api key, that was pretty dumb on my part.
